INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (1,'Greek salad','Greek',1);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (2,'Bean soup','Italian',2);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (3,'Pizza','Italian',3);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (4,'Carbonara','Turkish',4);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (5,'Kabasa','Greek',5);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (6,'Shwarma','Italian',6);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (7,'Greek salad','Italian',1);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (8,'Bean soup','Turkish',2);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (9,'Pizza','Greek',3);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (10,'Carbonara','Italian',4);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (11,'Kabasa','Italian',5);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (12,'Shwarma','Turkish',6);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (13,'Bean soup','Turkish',7);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (14,'Pizza','Greek',8);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (15,'Carbonara','Italian',9);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (16,'Kabasa','Italian',10);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (17,'Shwarma','Turkish',11);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (18,'Greek salad','Greek',12);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (19,'Bean soup','Italian',7);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (20,'Pizza','Italian',8);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (21,'Carbonara','Turkish',9);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (22,'Kabasa','Greek',10);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (23,'Shwarma','Italian',11);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (24,'Greek salad','Italian',12);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (25,'Pizza','Italian',13);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (26,'Carbonara','Turkish',14);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (27,'Kabasa','Greek',15);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (28,'Shwarma','Italian',16);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (29,'Greek salad','Italian',17);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (30,'Bean soup','Turkish',18);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (31,'Pizza','Greek',13);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (32,'Carbonara','Italian',14);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (33,'Kabasa','Italian',15);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (34,'Shwarma','Turkish',16);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (35,'Greek salad','Greek',17);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (36,'Bean soup','Italian',18);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (37,'Carbonara','Italian',19);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (38,'Kabasa','Italian',20);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (39,'Shwarma','Turkish',21);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (40,'Greek salad','Greek',22);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (41,'Bean soup','Italian',23);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (42,'Pizza','Italian',24);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (43,'Carbonara','Turkish',19);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (44,'Kabasa','Greek',20);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (45,'Shwarma','Italian',21);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (46,'Greek salad','Italian',22);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (47,'Bean soup','Turkish',23);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (48,'Pizza','Greek',24);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (49,'Kabasa','Greek',25);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (50,'Shwarma','Italian',26);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (51,'Greek salad','Italian',27);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (52,'Bean soup','Turkish',28);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (53,'Pizza','Greek',29);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (54,'Carbonara','Italian',30);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (55,'Kabasa','Italian',25);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (56,'Shwarma','Turkish',26);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (57,'Greek salad','Greek',27);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (58,'Bean soup','Italian',28);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (59,'Pizza','Italian',29);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (60,'Carbonara','Turkish',30);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (61,'Shwarma','Turkish',31);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (62,'Greek salad','Greek',32);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (63,'Bean soup','Italian',33);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (64,'Pizza','Italian',34);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (65,'Carbonara','Turkish',35);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (66,'Kabasa','Greek',36);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (67,'Shwarma','Italian',31);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (68,'Greek salad','Italian',32);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (69,'Bean soup','Turkish',33);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (70,'Pizza','Greek',34);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (71,'Carbonara','Italian',35);
INSERT INTO LittleLemonDB.Menus (MenuID, MenuName, Cuisine, MenuItemsID) VALUES (72,'Kabasa','Italian',36);

