INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (1, 'Tapas','Greek yoghurt','Olives','Athens White wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (2, 'Potato salad','Ice cream','Flatbread','Corfu Red Wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (3, 'Bruschetta','Cheesecake','Minestrone','Italian Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (4, 'Focaccia','Affogato','Tomato bread','Roma Red wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (5, 'Meatballs','Turkish yoghurt','Falafel','Ankara White Wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (6, 'Fries','Baklava','Hummus','Turkish Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (7, 'Potato salad','Ice cream','Olives','Corfu Red Wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (8, 'Bruschetta','Cheesecake','Flatbread','Italian Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (9, 'Focaccia','Affogato','Minestrone','Roma Red wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (10, 'Meatballs','Turkish yoghurt','Tomato bread','Ankara White Wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (11, 'Fries','Baklava','Falafel','Turkish Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (12, 'Tapas','Greek yoghurt','Hummus','Athens White wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (13, 'Bruschetta','Cheesecake','Olives','Italian Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (14, 'Focaccia','Affogato','Flatbread','Roma Red wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (15, 'Meatballs','Turkish yoghurt','Minestrone','Ankara White Wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (16, 'Fries','Baklava','Tomato bread','Turkish Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (17, 'Tapas','Greek yoghurt','Falafel','Athens White wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (18, 'Potato salad','Ice cream','Hummus','Corfu Red Wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (19, 'Focaccia','Affogato','Olives','Roma Red wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (20, 'Meatballs','Turkish yoghurt','Flatbread','Ankara White Wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (21, 'Fries','Baklava','Minestrone','Turkish Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (22, 'Tapas','Greek yoghurt','Tomato bread','Athens White wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (23, 'Potato salad','Ice cream','Falafel','Corfu Red Wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (24, 'Bruschetta','Cheesecake','Hummus','Italian Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (25, 'Meatballs','Turkish yoghurt','Olives','Ankara White Wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (26, 'Fries','Baklava','Flatbread','Turkish Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (27, 'Tapas','Greek yoghurt','Minestrone','Athens White wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (28, 'Potato salad','Ice cream','Tomato bread','Corfu Red Wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (29, 'Bruschetta','Cheesecake','Falafel','Italian Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (30, 'Focaccia','Affogato','Hummus','Roma Red wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (31, 'Fries','Baklava','Olives','Turkish Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (32, 'Tapas','Greek yoghurt','Flatbread','Athens White wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (33, 'Potato salad','Ice cream','Minestrone','Corfu Red Wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (34, 'Bruschetta','Cheesecake','Tomato bread','Italian Coffee');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (35, 'Focaccia','Affogato','Falafel','Roma Red wine');
INSERT INTO LittleLemonDB.MenuItems (MenuItemsID, CourseName, DesertName, StarterName, Drink) VALUES (36, 'Meatballs','Turkish yoghurt','Hummus','Ankara White Wine');

